version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8083:80"  # Expose Apache on port 9000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
